name: Review Assign

on:
  pull_request:
    types: [opened, ready_for_review, closed] # when using 'merged-comment', 'closed' event subscription required

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }} # assign pull request author
          reviewers: afarhood # if draft, assigned when draft is released
          ready-comment: 'Ready for review :rocket:' # if there are reviewers, posted when opened or draft is released
          merged-comment: 'It was merged. Thanks for your review :wink:' # if reviewed, posted when merged