name: Create Issue Branch
run-name: ${{ github.actor }} created an Issue
on:
  issues:
    types: [ assigned ]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
      - name: Testing uses
        uses: ./.github/issue-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}