name: Create Issue Branch
run-name: ${{ github.actor }} created an Issue
on:
  issues:
    types: [ assigned ]

jobs:
  create-issue-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  output-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Output
        uses: actions/checkout@v3
      - run: echo ${{ steps.create-issue-branch.outputs.branchName }}
        